---

- name: 'Create Docker data directory'
  file:
    path: "{{ docker_data_dir }}"
    state: directory
    mode: '0755'

- name: 'Set up Docker Swarm'
  include_tasks: 'docker_swarm.yml'

- name: "Deploy services"
  include_tasks: "{{ container }}.yml"
  loop: "{{ mandatory_services + enabled_services }}"
  loop_control:
    loop_var: 'container'
