---
- name: 'Create network'
  docker_network:
    name: 'portainer_agent_network'
    driver: 'overlay'

- name: 'Create directory for container data'
  file:
    path: "{{ docker_data_dir }}/portainer_data"
    state: 'directory'

- name: 'Deploy Portainer Agent'
  docker_swarm_service:
    name: 'portainer_agent'
    image: 'portainer/agent'
    env:
      - 'AGENT_CLUSTER_ADDR=tasks.portainer_agent'
    mounts:
      - source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        type: 'bind'
        readonly: yes
      - source: '/var/lib/docker/volumes'
        target: '/var/lib/docker/volumes'
        type: 'bind'
    networks:
      - 'portainer_agent_network'
    mode: 'global'
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.platform.os == linux'
    user: null

- name: 'Deploy Portainer'
  docker_swarm_service:
    name: 'portainer'
    image: 'portainer/portainer'
    command: '/portainer -H tcp://tasks.portainer_agent:9001 --tlsskipverify'
    env:
      - 'AGENT_CLUSTER_ADDR=tasks.portainer_agent'
    mounts:
      - source: "{{ docker_data_dir }}/portainer_data"
        target: '/data'
        type: 'bind'
    networks:
      - 'traefik_backend'
      - 'portainer_agent_network'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.portainer.entrypoints: 'http'
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_app_name }}.{{ traefik_domain }}`)"
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: 'https'
      traefik.http.routers.portainer.middlewares: 'https-redirect'
      traefik.http.routers.portainer-secure.entrypoints: 'https'
      traefik.http.routers.portainer-secure.rule: "Host(`{{ portainer_app_name }}.{{ traefik_domain }}`)"
      traefik.http.routers.portainer-secure.tls: 'true'
      traefik.http.routers.portainer-secure.tls.certresolver: 'letsencrypt'
      traefik.http.routers.portainer-secure.service: 'portainer'
      traefik.http.services.portainer.loadbalancer.server.port: '9000'
      traefik.docker.network: 'traefik_backend'

    mode: 'replicated'
    replicas: 1
    restart_config:
      condition: "{{ restart_condition }}"
    placement:
      constraints:
        - 'node.role == manager'
    user: null

